# File for testing the API 

# Variables
@token = 
@port = 8443
@host = https://localhost:{{port}}

###

GET {{host}}/api/trabajos/

###

# Crear un trabajo

POST {{host}}/api/trabajadores
# Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idTrabajador": "T004",
  "dni": "",
  "nombre": "Anaclet",
  "apellidos": "Agent Secret",
  "especialidad": "",
  "contraseña": "",
  "email": ""
}

###

